### ISSUE TITLE
Filters to be expressed as flag-string in query to make it shareable.

### ISSUE THREAD

**Issue by Maksims** [pyalot/webglstats-site#32]
Quiet often want to share link with stats covering only Android for example, but Filters are not preserved in URL query.

It would be useful if they would be, that would make all pages with their Filter states linkable.

Some implementation features:
1. Using History API to modify query url without redirecting.
2. Make bitmask and convert into character within valid ASCII letter space with numbers, that would be short enough for storing in query URL.

**Comment by pyalot** [comment]
I agree that sharing a filter setting with a page link would be helpful. I did do some preparatory work for this, however aparts from some auxilliary problems, the main problem is the bitmask would depend on what values are entered in the database. And this might change, so URLs would break. I can currently add new values to a column  and that wouldn't break urls, but I couldn't remove values.

I think it'd require versioning of the database schema/metadata, and I'm not quite there with that yet.

**Comment by Maksims** [comment]
That hash could have version number in beginning, and having single array of bit to filter relationship in JS will help to prevent re-ordering of filters screwing things up.

**Comment by pyalot** [comment]
I've thought about the version bit to include on compiled queries like that. I don't currently have the ability in the backend to deal with schema/meta versions (and automatically bumping, storing, comparing and converting them). I'd like to have that though.

**Comment by pyalot** [comment]
I think I can keep the platform list stable for now, and new entries are appended at the end. 2 bytes are reserved at the front for future use in versioning and whatnot.

**Comment by Maksims** [comment]
Awesome! This is cool. Just in time with Mozilla releasing WebGL 2 in Firefox, easier to track and share the stats about it :)
