### ISSUE TITLE
Showing incorrect results for WebGL2 extensions for iOS?

### ISSUE THREAD

**Issue by greggman** [pyalot/webglstats-site#38]
I'm probably doing something stupid but I'm a little confused.

AFAIK as of today, September 18th, 2017 iOS does not support WebGL2 and checking the WebGL2 stats that seems to be true

http://webglstats.com/webgl2?platforms=000000040000000000

But if I switch to the `OES_texture_float_linear` extension for **WebGL2** it shows 38% support. 

http://webglstats.com/webgl2/extension/OES_texture_float_linear?platforms=000000040000000000

Is that a bug?

**Comment by pyalot** [comment]
That isn't a bug. Some UAs send a user-agent string that makes them look like iOS (so there'll be always a small percentage of support on platforms that ostensibly do not have support). It's obvious that the presence or absence of an extension can only be tested if a webgl context is supported, so the statistic of 38% tells you how many of those signaling support for WebGL2, have support for that extension. The statistics for an extension do not mean either not having webgl or not having the extension or having both. They just mean having the extension or not having the extension.

**Comment by greggman** [comment]
I guess I don't understand how that's possible. the stats show zero support for WebGL2 for iOS but greater than zero for WebGL2 extensions . How do you get a positive iOS number for an extension if you could not create the WebGL2 context in the first place to check for the extension?

maybe you're only checking for the existence of the extension object but then that's not really useful info since it does tell me if the device supports the extension only that the browser shows the object

I also I guess I don't understand how if the issue is a browser that's not iOS  that claims it's iOS shouldn't that same broswers show up under WebGL2 by the same logic? and yet they are not. why wouldnt those same machines show under both webgl2 and the extension. ?

**Comment by pyalot** [comment]
Zero percent rounded. If you look at the number there's still 14'300 impressions claiming to be iOS supporting WebGL2.
