### ISSUE TITLE
webglstats.com 502 Bad Gateway

### ISSUE THREAD

**Issue by jimbojw** [pyalot/webglstats-site#43]
webglstats.com appears to be down, serving a 502 Bad Gateway response from nginx. Also the HTTPS certificate expired on February 16.

**Comment by greggman** [comment]
Just FYI I really appreciate this site. I know you probably don't get a lot of thanks but sincerely, thank you for running this. If you plan to fix it that would be great. If not that would also be nice to know. In either case, thanks for all the years of running this. It's been super useful to me.

**Comment by marquizzo** [comment]
@pyalot And also, if there's anything we can do to help support the site, let us know! I'd love to help if possible!

**Comment by munrocket** [comment]
Best site about webgl extensions, ever.

**Comment by marquizzo** [comment]
Site is back up! http://webglstats.com/ 
@jimbojw I guess you can close this issue now! 😃

**Comment by munrocket** [comment]
Finally, website is back 🎉
